export type ErrorCode =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'INTERNAL_ERROR'
  | 'VALIDATION_ERROR'
  | 'UNIQUE_CONSTRAINT'

  // FRIENDSHIP DOMAIN
  | 'FRIENDSHIP_SELF_REQUEST'
  | 'FRIENDSHIP_ALREADY_EXISTS'
  | 'FRIENDSHIP_NOT_PENDING'
  | 'FRIENDSHIP_FORBIDDEN';