export enum ErrorCode {
  HTTP_ERROR = 'HTTP_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}